BLOCK = "{", { COMMAND }, "}" ;
COMMAND = ( λ | ASSIGNMENT | PRINT | WHILE | IF), ";" | BLOCK ;
ASSIGNMENT = IDENTIFIER, "=", RELEXPR, ";" ;
WHILE = WHILE, RELEXPR, BLOCK, ";" ;
IF = IF, RELEXPR, BLOCK , (";" | ELSE, BLOCK, ';') ;
PRINT = "echo", RELEXPR, ";" ;
RELEXPR = EXPRESSION, { ("==" | ">" | "<"), EXPRESSION } ;
EXPRESSION = TERM, { ("+" | "-"), TERM } ;
TERM = FACTOR, { ("*" | "/"), FACTOR } ;
FACTOR = (("+" | "-" | "!"), FACTOR) | NUMBER | "(", EXPRESSION, ")" | IDENTIFIER | READLINE ;
IDENTIFIER = "$", LETTER, { LETTER | DIGIT | "_" } ;
READLINE = "input()" ;
NUMBER = DIGIT, { DIGIT } ;
LETTER = ( a | ... | z | A | ... | Z ) ;
DIGIT = ( 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 ) ;